### ISSUE TITLE
PSARips Rss Feed not Working

### ISSUE THREAD

**Issue by sherlockia2** [viperadnan-git/rss-feed-telegram-bot#3]
https://x265.club/feed/ --> This RSS feed link is not working.
Traceback (most recent call last):

2021-04-24T03:34:57.746218+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job

2021-04-24T03:34:57.746219+00:00 app[worker.1]:     retval = job.func(*job.args, **job.kwargs)

2021-04-24T03:34:57.746219+00:00 app[worker.1]:   File "/app/rss.py", line 33, in check_feed

2021-04-24T03:34:57.746274+00:00 app[worker.1]:     entry = FEED.entries[0]

2021-04-24T03:34:57.746275+00:00 app[worker.1]: IndexError: list index out of range

**Comment by sherlockia2** [comment]
@viperadnan-git  Any update on this bro?
